# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44b9154ce052495cc4962639add2269e27d5943d7db78dcc0df8d9326f9c73044ed5c2cdf959706b594ed614dd325dcb7b87ddb992a8c7b8c73fdab09a9ae29e

test:
  secret_key_base: bd0d76ad029e11456aa0ab17b734203707d4ee9b453cc57114fd7d63d2075a08797022f2f88094706699e5d3987090c15a35d2a9967e0bef1aff19f47518d9d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
